### PR TITLE
fix(YouTube/Spoof streaming data): Log out the iOS client to allow video playback

### LINKED ISSUE #2508: bug(YouTube/Spoof streaming data): Spoofing does not work with `iOS`
### Type

Error at runtime

### Tools used

rvx-builder

### Application

Youtube 19.16.39

### Bug description

Youtube has always played videos in their native language and if more than 1 audio track was available it was possible to change it via the track selection option in the player settings.

I have used Youtube 19.16.39 with the latest patches to date (4.16.1) since they came out and the track selection option has always been there, however since yesterday I am getting AI translated audio in non English speaking videos and all of a sudden the audio track selection option has gone missing (I have read that Youtube is pushing out AI translated audio so that may be the culprit?).

I am attaching a .txt file with the settings I am currently using.

[Revanced Extended options.txt](https://github.com/user-attachments/files/17930455/Revanced.Extended.options.txt)

### Error logs

_No response_

### Solution

_No response_

### Additional context

_No response_

### Device Environment

Galaxy S10+ SM-G975F Android 10

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

### PR DESCRIPTION
**Pull request by YT-Advanced**
Fix https://github.com/inotia00/ReVanced_Extended/issues/2508
Right now, YouTube has restricted the auth token in `iOS` client. 
https://github.com/yt-dlp/yt-dlp/issues/11640#issuecomment-2501049515

To workaround with this issues, we can remove `Authorization` header from `iOS` client and manual sync video time in iOS Livestream.

Here are some example how this patch work:
- Public video + livestreams: iOS
- Private video, not kids: ANDROID_VR
- Private kids video, not music: ANDROID_UNPLUGGED
- Private kids video, but music: Fail

Patches changes: https://github.com/inotia00/revanced-patches/pull/100/

### CODE REVIEW

**Comment by Karthik-Subbu** [comment]
@YT-Advanced and @inotia00  clients like mweb.ios without login or web_creator.mweb with authentication would be of any use to us?

The relevant PR in yt-dlp is below:

https://github.com/yt-dlp/yt-dlp/pull/11663/commits/85fead78b2dd9af3f3f0c2ccb35fe282eff29088

File: app/src/main/java/app/revanced/integrations/youtube/patches/misc/SpoofStreamingDataPatch.java [hunk 1]
```diff
@@ -180,6 +181,15 @@ public static String appendSpoofedClient(String videoFormat) {
         return videoFormat;
     }
 
+    /**
+     * Injection point.
+     */
+    public static void syncLivestreamTime(TextView view) {
+        Utils.runOnMainThreadDelayed(() -> {
+            if (view != null) view.performClick();
```
Comment (inotia00) [inline app/src/main/java/app/revanced/integrations/youtube/patches/misc/SpoofStreamingDataPatch.java]: This is not ideal

Because it doesn't work as intended in the following cases:

1. Shorts livestream (in Shorts, the `Skip to Livestream` button is a litho component)
2. When the livestream is playing from a feed, not player (`TimeBarLiveLabel` is not initialized)
3. When the video already starts at the current time (some livestreams start at the current time, not at 0 seconds on iOS clients, so clicking on `TimeBarLiveLabel`, it skips to 0 seconds)

**Comment by inotia00** [comment]
Manually clicking the `Skip to Livestream` button doesn't work properly in many situations

It seems better to keep the `iOS Compatibility mode` setting and reopen the PR https://github.com/inotia00/revanced-integrations/pull/59
